version: "3.6"
services:
  db:
    image: mysql:5.7
    container_name: avito_crud
    volumes:
      # настройки mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: avito_crud
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: my_app
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    #volumes:
    #  - api:/usr/src/app/
    #networks:
    # - fullstack
    environment:
      connStr: "host=db password=pass dbname=avito_crud port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      waitTime: "120s"

