version: "3.6"
services:
  db:
    image: mysql:5.7
    container_name: avito_crud
    volumes:
      # настройки mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: avito_crud
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
